/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sheldongame;
/**
 *
 * @author Andre Marin
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainWindow() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Player");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Machine");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Wins");

        jButton1.setText("Rock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Scissors");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Paper");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Lizard");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Spock");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Rules");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6)
                            .addComponent(jButton5))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Character characterRock= new Character(1);
        Character characterPaper = new Character(2);
        Character characterScissors = new Character(3);
        Character characterLizard = new Character(4);
        Character characterSpock = new Character(5);
        Opponent machine = new Opponent();
        checkRock(characterRock, characterPaper, characterScissors, characterLizard, characterSpock, machine);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         InstructionsWindow instructions = new InstructionsWindow(this,true);
         instructions.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Character characterRock= new Character(1);
        Character characterPaper = new Character(2);
        Character characterScissors = new Character(3);
        Character characterLizard = new Character(4);
        Character characterSpock = new Character(5);
        Opponent machine = new Opponent();
        checkScissors(characterRock, characterPaper, characterScissors, characterLizard, characterSpock, machine);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Character characterRock= new Character(1);
        Character characterPaper = new Character(2);
        Character characterScissors = new Character(3);
        Character characterLizard = new Character(4);
        Character characterSpock = new Character(5);
        Opponent machine = new Opponent();
        checkPaper(characterRock, characterPaper, characterScissors, characterLizard, characterSpock, machine);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Character characterRock= new Character(1);
        Character characterPaper = new Character(2);
        Character characterScissors = new Character(3);
        Character characterLizard = new Character(4);
        Character characterSpock = new Character(5);
        Opponent machine = new Opponent();
        checkLizard(characterRock, characterPaper, characterScissors, characterLizard, characterSpock, machine);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Character characterRock= new Character(1);
        Character characterPaper = new Character(2);
        Character characterScissors = new Character(3);
        Character characterLizard = new Character(4);
        Character characterSpock = new Character(5);
        Opponent machine = new Opponent();
        checkSpock(characterRock, characterPaper, characterScissors, characterLizard, characterSpock, machine);
    }//GEN-LAST:event_jButton5ActionPerformed
    public void checkRock(Character characterRock1, Character characterPaper1, Character characterScissors1, Character characterLizard1, Character characterSpock1,Opponent machine1){
        jLabel1.setText("You are Rock");
        if (machine1.getAttack() == characterRock1.getAttack()){
            jLabel3.setText("Its a draw");
            jLabel2.setText("Machine is a Rock");
        }
        else{
            if((machine1.getAttack() == characterPaper1.getAttack())){
               jLabel3.setText("Paper cover Rocke, you lose");
                jLabel2.setText("Machine is a Paper");
            }
            else{
                if ((machine1.getAttack() == characterScissors1.getAttack())){
                    jLabel3.setText("Rock crushes Scissors, you win");
                    jLabel2.setText("Machine is a Scissors");
                }
                else{
                    if((machine1.getAttack() == characterLizard1.getAttack())){
                        jLabel3.setText("Rock crushes lizard, you win");
                        jLabel2.setText("Machine is a Lizard");
                    }
                    else{
                        if((machine1.getAttack() == characterSpock1.getAttack())){
                            jLabel3.setText("Spock vaporizes rock, you lose");
                            jLabel2.setText("Machine is a Spock");
                        }
                    }
                }
            }
        }
    }
    public void checkPaper(Character characterRock1, Character characterPaper1, Character characterScissors1, Character characterLizard1, Character characterSpock1,Opponent machine1){
        jLabel1.setText("You are Papper");
        if (machine1.getAttack() == characterPaper1.getAttack()){
            jLabel3.setText("Its a draw");
            jLabel2.setText("Machine is a Paper");
        }
        else{
            if((machine1.getAttack() == characterRock1.getAttack())){
                jLabel3.setText("Paper cover Rock, you win");
                jLabel2.setText("Machine is a Rock");
            }
            else{
                if ((machine1.getAttack() == characterScissors1.getAttack())){
                    jLabel3.setText("Scissors cuts paper, you lose");
                    jLabel2.setText("Machine is a Scissors");
                }
                else{
                    if((machine1.getAttack() == characterLizard1.getAttack())){
                        jLabel3.setText("Lizard eats paper, lose");
                        jLabel2.setText("Machine is a Lizard");
                    }
                    else{
                        if((machine1.getAttack() == characterSpock1.getAttack())){
                            jLabel3.setText("Paper disproves Spock, you win");
                            jLabel2.setText("Machine is a Spock");
                        }
                    }
                }
            }
        }
    }
     public void checkScissors(Character characterRock1, Character characterPaper1, Character characterScissors1, Character characterLizard1, Character characterSpock1, Opponent machine1){
        jLabel1.setText("You are Scissors");
         if (machine1.getAttack() == characterScissors1.getAttack()){
            jLabel3.setText("Its a draw");
            jLabel2.setText("Machine is a Scissors");
        }
        else{
            if((machine1.getAttack() == characterRock1.getAttack())){
                jLabel3.setText("Rock crushes Scissors, you lose");
                jLabel2.setText("Machine is a Rock");
            }
            else{
                if ((machine1.getAttack() == characterPaper1.getAttack())){
                    jLabel3.setText("Scissors cuts paper, you win");
                    jLabel2.setText("Machine is a Paper");
                }
                else{
                    if((machine1.getAttack() == characterLizard1.getAttack())){
                        jLabel3.setText("Scissors decapitates lizard, win");
                        jLabel2.setText("Machine is a Lizard");
                    }
                    else{
                        if((machine1.getAttack() == characterSpock1.getAttack())){
                            jLabel3.setText("Spock smashes scissors, you lose");
                            jLabel2.setText("Machine is a Spock");
                        }
                    }
                }
            }
        }
    }
    public void checkLizard(Character characterRock1, Character characterPaper1, Character characterScissors1, Character characterLizard1, Character characterSpock1,Opponent machine1){
        jLabel1.setText("You are Lizard");
        if (machine1.getAttack() == characterLizard1.getAttack()){
            jLabel3.setText("Its a draw");
            jLabel2.setText("Machine is a Lizard");
        }
        else{
            if((machine1.getAttack() == characterRock1.getAttack())){
                jLabel3.setText("Rock crushes Lizard, you lose");
                jLabel2.setText("Machine is a Rock");
            }
            else{
                if ((machine1.getAttack() == characterPaper1.getAttack())){
                    jLabel3.setText("Lizard eats paper, you win");
                    jLabel2.setText("Machine is a Paper");
                }
                else{
                    if((machine1.getAttack() == characterScissors1.getAttack())){
                        jLabel3.setText("Scissors decapitates lizard, lose");
                        jLabel2.setText("Machine is a Scissors");
                    }
                    else{
                        if((machine1.getAttack() == characterSpock1.getAttack())){
                            jLabel3.setText("Lizard poisons Spock, you win");
                            jLabel2.setText("Machine is a Spock");
                        }
                    }
                }
            }
        }
    }
    public void checkSpock(Character characterRock1, Character characterPaper1, Character characterScissors1, Character characterLizard1, Character characterSpock1,Opponent machine1){
        jLabel1.setText("You are Spock");
        if (machine1.getAttack() == characterSpock1.getAttack()){
            jLabel3.setText("Its a draw");
            jLabel2.setText("Machine is a Spock");
        }
        else{
            if((machine1.getAttack() == characterRock1.getAttack())){
                jLabel3.setText("Spock vaporizes rock, you win");
                jLabel2.setText("Machine is a Rock");
            }
            else{
                if ((machine1.getAttack() == characterPaper1.getAttack())){
                    jLabel3.setText("Paper disproves Spock, you lose");
                    jLabel2.setText("Machine is a Paper");
                }
                else{
                    if((machine1.getAttack() == characterScissors1.getAttack())){
                        jLabel3.setText("Spock smashes scissors, win");
                        jLabel2.setText("Machine is a Scissors");
                    }
                    else{
                        if((machine1.getAttack() == characterLizard1.getAttack())){
                            jLabel3.setText("Lizard poisons Spock, you lose");
                            jLabel2.setText("Machine is a Lizard");
                        }
                    }
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
